language: cpp

jobs:
  include:
    - os: linux
      dist: focal
      env: TYPE=Debug

    - os: linux
      dist: focal
      env: TYPE=Release

    - os: linux
      arch: arm64
      dist: focal
      env: TYPE=Debug

    - os: linux
      arch: arm64
      dist: focal
      env: TYPE=Release

    - os: osx
      env: TYPE=Release

    - os: osx
      env: TYPE=Debug

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
  - python install.py -install -tool -ot
  - cd emp-tool; cmake -DENABLE_FLOAT=On .; sudo make install; cd .. 

script:
  - cmake -DCMAKE_BUILD_TYPE=$TYPE -DENABLE_FLOAT=On . && make 
  - ./run ./bin/bit
  - ./run ./bin/int
  - ./run ./bin/float
  - ./run ./bin/repeat
